<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
//use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * soortactiviteitenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoortactiviteitRepository extends EntityRepository
{

//    public function findAll()
//    {
////        return [];
//        return $this->findBy(array(),array('datum'=>'ASC'));
//    }

}
